version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/src/client
      - /src/client/node_modules

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '80:80'
    volumes:
      - ./server:/src/server
      - /src/server/node_modules
    depends_on:
      - mongodb
    networks:
      - node-network

  mongodb:
    image: mongo:5.0.19
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
