version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/src/client
      - /src/client/node_modules
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./server:/src/server
      - /src/server/node_modules
