const COMMENT_PER_REQUEST = 20;
const POST_PER_REQUEST = 10;

const ENGAGEMENT_WEIGHT = 0.45;
const RECENCY_WEIGHT = 0.05;
const RELEVANCE_WEIGHT = 0.5;
const MILLISECONDS_IN_HOUR = 3600000;

module.exports = {
  COMMENT_PER_REQUEST,
  POST_PER_REQUEST,
  ENGAGEMENT_WEIGHT,
  RELEVANCE_WEIGHT,
  RECENCY_WEIGHT,
  MILLISECONDS_IN_HOUR,
};
